### ISSUE TITLE
docs: Smart time entry examples don't seem to reflect actual parsing

### ISSUE THREAD

**Issue by lukestein** [cpvalente/ontime-docs#33]
*Installation*: v3.0.2 via Docker (Synology NAS)

---

Examples on the [smart time entry documentation](https://docs.getontime.no/quick-tips/smart-time-entry) don't seem to reflect actual parsing. For example

- `0.1` `0 1` `0:1` `0,1` → All seem to yield one minute (not one second as docs suggest
- `120` → 1:20:00 (not 120 minutes)
- `0.120` → 2:00:00 (not 120 seconds)

**Comment by cpvalente** [comment]
Thank you @lukestein , I took some time to review these I see that we changed the specification and forgot to update the docs. This happened some time back when we made v2 🫠 

I am inclined to believe that the new version is better as is more inline with expectations, however your examples outlined a few issues.

In the current implementation, we make the initial unit minutes and second unit hours. we also cap inputs at two digits.
That gives is the behaviour you experienced with
`20` -> 20 minutes
`120` -> 1 hour + 20 minutes
`90m` -> 90 minutes

`0.1` `0 1` `0:1` `0,1` → 0 hours + 1 minute, seems ok to me
`0.120` → ??? 0 hours 12 minutes 0 seconds?

I see that our logic opens up to inconsistency and I was wondering if you have any opinion on this last edge cases?

**Comment by lukestein** [comment]
> I am inclined to believe that the new version is better as is more inline with expectations, however your examples outlined a few issues.

I suspect the current parser is great, so this is just a documentation issue.

> `0.1` `0 1` `0:1` `0,1` → 0 hours + 1 minute, seems ok to me `0.120` → ??? 0 hours 12 minutes 0 seconds?
> 
> I see that our logic opens up to inconsistency and I was wondering if you have any opinion on this last edge cases?

I'm not very opinionated on this, but I think the most important thing is to give reasonable/expected output *for reasonable input*.

I think `120` could reasonably be interpreted as either 120 minutes or 1:20, so it's fine to have chosen the latter.

It's totally unclear to me what a user might expect when typing in 0.120 so honestly I don't think it matters very much how it's parsed.

Thinking about this a bit highlights for me how difficult the task is to achieve perfectly, so I think consistency in terms of documentable rules may trump "accuracy" in terms of predicting user intent. As one example, *for me*, it makes more sense that for a duration,
- `1.5` is 1:30
- `1.50` is 1:50
- `150` is 2:30
- `1.05` is 1:05
- `105` is 1:45
but that some could naturally get interpreted differently for a time rather than a duration (e.g., `105` as a time is 1:05). Plus the first two could wreck havoc on eg spreasheet imports since as numbers, `1.5 == 1.50`.

All of which is to say… I'd suggest not changing the parser, but trying to update the documentation to match.

**Comment by cpvalente** [comment]
Hi @lukestein, I apologise that I closed the issue with the merge.
I have updated the docs with some supporting tests and hopefully things are clearer now.

Thank you again for bringing this up, your help has been incredible.
Feel free to reopen if this needs further work

**Comment by lukestein** [comment]
Glad to be (a tiny bit of) service @cpvalente.

I hope you won't mind I've taken the liberty of suggesting some edits in #35. Feel free to reject that pull request, edit as you wish, etc.

**Comment by cpvalente** [comment]
No problem at all @lukestein
It is great to have users help keeping the documentation up to date
